### ISSUE TITLE
Unknown Motherboard in configuration.h

### ISSUE THREAD

**Issue by cctvfm** [sky8000/SKR-Mini-E3-Ender-5-Config-Files-Marlin-2#1]
In configuration.h

#define MOTHERBOARD BOARD_BIGTREE_SKR_MINI_E3

should be changed to 

 #define MOTHERBOARD BOARD_BTT_SKR_MINI_E3_V1_0

**Comment by cgsneves** [comment]
Fixed motherboard configuration.
Thanks.
