### ISSUE TITLE
platform.ini 

### ISSUE THREAD

**Issue by Reefwalker** [sky8000/SKR-Mini-E3-Ender-5-Config-Files-Marlin-2#2]
Hi Sky8000,
I had issues with my Ender5 as I updated the firmware to the new version.  So I used yours here with the BLTouch

After following your instructions, it will not compile.  Seems the default_envs is set as STM32F103RC_bigtree

It should be STM32F103RC_btt.

Also, before compiling, I jumped into configuration.h and changed the z_probe_offest to my own numbers.

Thanks very much for doing this.  After making the above changes it worked perfectly.

**Comment by sky8000** [comment]
Hi,

Thank you so much for reporting this problem.
I'll fix it in next commit.
