### ISSUE TITLE
Error on compile

### ISSUE THREAD

**Issue by sambwest** [sky8000/SKR-Mini-E3-Ender-5-Config-Files-Marlin-2#3]
Having the following in the configuration files causes a compile error with the latest version. Commenting out fixes. 

// #define X_HOME_BUMP_MM 5
// #define Y_HOME_BUMP_MM 5
// #define Z_HOME_BUMP_MM 2

**Comment by sky8000** [comment]
Hi,

Thanks for the feedback.

Just updated the repo with fixed config files that are now compatible with Marlin 2.0.6.
