### ISSUE TITLE
Marlin 2.x board name changes

### ISSUE THREAD

**Issue by selalipop** [sky8000/SKR-Mini-E3-Ender-5-Config-Files-Marlin-2#4]
On the latest 2.x builds SKR's board was renamed to `STM32F103RC_btt` from `STM32F103RC_bigtree`

Mostly a heads up for anyone trying to use a more recent build

**Comment by selalipop** [comment]
Looks like the motherboard was also renamed to `BOARD_BTT_SKR_MINI_E3_V1_0`

**Comment by sky8000** [comment]
Hi,

Thanks for the feedback.

Just updated the repo with fixed config files that are now compatible with Marlin 2.0.6.
